//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDataPribadi
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using Microsoft.AspNetCore.Mvc;

    public partial class DataDB
    {
        [Key]
        [Required(ErrorMessage = "Mohon Isi NIK Anda")]
        [Remote("IsNIKExist", "Home", ErrorMessage = "NIK telah terdaftar")]
        [StringLength(16, MinimumLength = 16, ErrorMessage = "NIK harus terdiri dari 16 angka")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "NIK hanya berisi angka")]
        public string NIK { get; set; }

        [Required(ErrorMessage = "Mohon Isi Nama Anda")]
        [Display(Name = "Nama Lengkap")]
        public string Nama_Lengkap { get; set; }
        
        [Display(Name = "Jenis Kelamin")]
        public string Jenis_Kelamin { get; set; }
        
        [Display(Name = "Tanggal Lahir")]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Tanggal_Lahir { get; set; }

        public string Alamat { get; set; }
        [Display(Name = "Negara")]

        public int CountryId { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
